import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-center py-6 mb-3 text-amber-200 text-3xl ">
          Header
        </header>
        <hr className="mb-10"></hr>
        {children}

        <footer className="flex items-center justify-center py-6 text-amber-200 text-3xl ">
          Footer
        </footer>
      </body>
    </html>
  );
}
